BatyaBlog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.flatpages import urls
from django.contrib.sitemaps.views import sitemap
from posts.sitemap import ASitemap


sitemaps = {
    'posts': ASitemap()
}


urlpatterns = [
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^user/', include("profiles.urls", namespace='profiles')),
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include(urls)),
    url(r'^', include("posts.urls", namespace='posts')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import (
        Mainpage,
        create,
        Detail,
        update,
        delete,
        TagListView,
        robots,
    )


urlpatterns = [
    url(r'^$', Mainpage.as_view(), name='mainpage'),
    url(r'^health/$', Mainpage.as_view(), name='health'),
    url(r'^growth/$', Mainpage.as_view(), name='growth'),
    url(r'^things/$', Mainpage.as_view(), name='things'),
    url(r'^dosug/$', Mainpage.as_view(), name='dosug'),
    url(r'^create/$', create, name='create'),
    url(r'^tag/(?P<slug>[\w-]+)/$', TagListView.as_view(), name='tagged'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/$', Detail.as_view(), name='detail'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/edit/$', update, name='update'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/delete/$', delete),

    url(r'^robots.txt$', robots),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.utils.text import slugify
from unidecode import unidecode
from posts.utils import categories
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from taggit.managers import TaggableManager


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=150, blank=False)
    image = models.ImageField(upload_to=upload_location,
                              null=True, blank=True, height_field='height_field', width_field='width_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    previewText = models.TextField(max_length=260, blank=True)
    fullText = models.TextField()
    slug = models.SlugField(max_length=150, unique=True)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    category = models.CharField(max_length=40, choices=categories(), default='CH')
    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self, *args, **kwargs):
        if self.category == u'Здоровье':
            cat = "health"
        elif self.category == u'Развитие':
            cat = "growth"
        elif self.category == u'Вещи':
            cat = "things"
        elif self.category == u'Досуг':
            cat = "dosug"
        return reverse("posts:detail", kwargs={"category": cat, "slug": self.slug})

    class Meta:
        ordering = ["-timestamp"]


def create_slug(instance, new_slug=None):
    slug = slugify(unidecode(instance.title))
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (instance, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from datetime import date
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget


class PostForm(forms.ModelForm):
    previewText = forms.CharField(widget=PagedownWidget(show_preview=False))
    fullText = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget, initial=date.today())

    class Meta:
        model = Post
        fields = [
            'title',
            'draft',
            'image',
            'previewText',
            'fullText',
            'category',
            'tags',
            'publish',
        ]

posts/views.py
from django.http import Http404, HttpResponseRedirect, request
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.db.models import Q
from .models import Post
from .forms import PostForm
from django.views.generic import ListView, DetailView
from taggit.models import Tag


class Mainpage(ListView):
    template_name = "posts/postlist.html"
    paginate_by = "3"
    all_tags = Tag.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_tags'] = Tag.objects.all()
        return context

    def get_queryset(self):
        q = self.request
        q = str(q)

        query = self.request.GET.get('q')
        print(query)
        if query:
            return Post.objects.all().filter(
                Q(title__icontains=query) |
                Q(category__icontains=query) |
                Q(previewText__icontains=query) |
                Q(fullText__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)
            )

        if self.request.method == 'GET' and '/health/' in q:
            return Post.objects.all().filter(category__iexact='Здоровье')
        elif self.request.method == 'GET' and '/things/' in q:
            return Post.objects.all().filter(category__iexact='Вещи')
        elif self.request.method == 'GET' and '/growth/' in q:
            return Post.objects.all().filter(category__iexact='Развитие')
        elif self.request.method == 'GET' and '/dosug/' in q:
            return Post.objects.all().filter(category__iexact='Досуг')
        else:
            return Post.objects.all()


def create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        form.save_m2m()
        messages.success(request, "Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context)


class Detail(DetailView):
    template_name = 'posts/detail.html'
    model = Post


def update(request, slug=None, *args, **kwargs):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        form.save_m2m()
        messages.success(request, "Updated")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'instance': instance,
        'form': form,
    }
    return render(request, 'posts/create.html', context)


def delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Удалено")
    return redirect('posts:mainpage')


class TagListView(ListView):
    template_name = "posts/postlist.html"
    paginate_by = "3"

    def get_queryset(self, *args, **kwargs):
        return Post.objects.filter(tags__slug=self.kwargs.get("slug")).all()

    def get_context_data(self, *args, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        context["tag"] = self.kwargs.get("slug")
        return context


def robots(request):
    return render_to_response('robots.txt', content_type='text/plain')

#
#              PAGES CLASSES
#


# class Health(ListView):
#     template_name = "posts/postlist.html"
#     paginate_by = "3"
#
#     def get_queryset(self):
#         q = self.request
#         q = str(q)
#         print(q)
#
#         if self.request.method == 'GET' and '/health/' in q:
#             return Post.objects.all().filter(category__iexact='Здоровье')
#         elif self.request.method == 'GET' and '/things/' in q:
#             return Post.objects.all().filter(category__iexact='Досуг')
#         elif self.request.method == 'GET' and '/things/' in q:
#             return Post.objects.all().filter(category__iexact='Досуг')
#         elif self.request.method == 'GET' and '/things/' in q:
#             return Post.objects.all().filter(category__iexact='Досуг')
#         else:
#             return Post.objects.all()
#
#
# class Things(ListView):
#     template_name = "posts/postlist.html"
#     paginate_by = "3"
#
#     def get_queryset(self):
#         return Post.objects.all().filter(category__iexact='Вещи')
#
#
# class Dosug(ListView):
#     template_name = "posts/postlist.html"
#     paginate_by = "3"
#
#     def get_queryset(self):
#         return Post.objects.all().filter(category__iexact='Досуг')
#
#
# class Growth(ListView):
#     template_name = "posts/postlist.html"
#     paginate_by = "3"
#
#     def get_queryset(self):
#         return Post.objects.all().filter(category__iexact='Развитие')

templates/posts/create.html
{% extends "index.html" %}

{% block title %}ПапаБлог - Добавить запись{% endblock title %}

{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block sidebar %}{% endblock sidebar %}

{% block content %}
<div class="col-sm-6">
    <p>Редактор</p>
    <form method="POST" id="post-form" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input type="submit" class="btn btn-default" value="Добавить" />
    </form>
</div>
<div class="col-sm-6">
    <p>Превью</p>
    <h3 id="preview-title"></h3>
    <img id="preview-image" src="" />
    <p id="preview-preview"></p>
    <p id="preview-full"></p>
</div>
{% endblock content %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function () {
            $(".col-md-9").each(function () {
               $(this).addClass("col-md-12");
               $(this).removeClass("col-md-9");
            });
        });

{#        var titleItem = $("#id_title");#}
{#        $("#preview-title").html(marked(titleItem.val()));#}

        var imageItem = $("label[for='id_image']").next().attr('href');
        $("#preview-image").attr('src', imageItem);

        var titleInput = $("#id_title");
        var previewInput = $("#id_previewText");
        var contentInput = $("#id_fullText");


        function setContent(value) {
            var markedContent = marked(value);
            $("#preview-full").html(markedContent);
        }
        setContent(contentInput.val());
        contentInput.keyup(function () {
            var newContent = $(this).val();
            setContent(newContent);
        });


        function setPreview(value) {
            var markedContent = marked(value);
            $("#preview-preview").html(markedContent);
        }
        setPreview(previewInput.val());
        previewInput.keyup(function () {
            var newContent = $(this).val();
            setPreview(newContent);
        });


        function setTitle(value) {
            var markedContent = marked(value);
            $("#preview-title").html(markedContent);
        }
        setTitle(titleInput.val());
        titleInput.keyup(function () {
            var newContent = $(this).val();
            setTitle(newContent);
        })
    </script>
{% endblock script %}

templates/posts/detail.html
{% extends "index.html" %}
{% load disqus_tags %}
{% load static %}

{% block description %}{{ object.previewText }}{% endblock description %}
{% block title %}ПапаБлог - {{ object.title }}{% endblock title %}

<div class="row">
{% block content %}

<div class="col-md-12 w-100">
    <div class="single-post">

    <!-- ___Start Article & Feature___ -->
        <div class="article-and-feature post-bottom-content bg-box-shadow each-section" data-scroll-index="0">
            <h3>{{ object.title }}</h3>
            <div class="meta-info">
                <p class="date"><i class="icon-clock"></i>{{ object.publish }}</p>
                <p class="category"><i class="icon-bookmark"></i>  <a href="/{% if object.category == 'Здоровье' %}health{% elif object.category == 'Развитие' %}growth{% elif object.category == 'Вещи' %}things{% elif object.category == 'Досуг' %}dosug{% endif %}/">{{ object.category }}</a> </p>
                <p class="author"><i class="icon-user"></i> by <a href="/user/{{ object.user }}">{{ object.user }}</a></p>
                {% if object.draft %}
                    <p class="author"><i class="fa fa-user"></i><span style="color: red">Черновик</span></p>
                {% endif %}
                <p class="comments-count"><i class="icon-commenting"></i> <a href="#disqus_thread"></a></p>
                {% if request.user.is_authenticated and request.user.is_staff %}
                    <p style="align-self: right"><a href="{{ object.get_absolute_url }}edit" title="Редактировать">Редактировать</a></p>
                {% endif %}
            </div>

            {% if object.image %}
                <img src="{{ object.image.url }}" alt="{{ object.title }}" class="img-responsive" />
            {% endif %}

            <div class="article-content">
                <div class="content-markdown">{{ object.fullText }}</div>
            </div>

            <!-- ___Start Post Meta___ -->
            <div class="post-meta">
                <div class="share-icon">
                    <i class="icon-share"></i>
                    <span>25 Share</span>
                </div>

                <div class="tags text-right">
                    <ul class="tag-mobile">
                        <li>Тэги: </li>
                        {% for tag in object.tags.all %}
                            <li><a href="{% url "posts:tagged" tag.slug %}">{{ tag.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div><!-- End Tags -->
            </div><!-- End Meta Post -->
        </div><!-- End Article & Feature -->

</div>




<!-- Информация об авторе -->
    <div data-scroll-index="3" class="each-section single-post-author common-border">
        <div class="row">
            <div class="col-lg-2 post-author-left">
                <img src="{{ object.user.profile.avatar.url }}" alt="">
            </div>
            <div class="col-lg-10 post-author-right">
                <h4>{{ object.user.get_full_name }}</h4>
                <p class="author-bio">{{ object.user.profile.bio }}</p>
                <a href="/user/{{ object.user }}" class="view-my-articles"><i class="fa fa-heart"></i>Все статьи автора</a>
            </div>
        </div><!-- End Row -->
    </div>


<!-- Добавить Комментарий -->
{#    <div data-scroll-index="5" class="each-section leave-a-comment">#}
{#    <h3>Комментировать</h3><a name="comments"></a>#}
{#    <div class="comment-form common-border">#}
{#        <div class="row">#}
{#            <form>#}
{#                <!-- ___Send Name Email Website___ -->#}
{#                <div class="col-lg-6">#}
{#                    <div class="form-group">#}
{#                        <label for="name">Имя</label>#}
{#                        <input type="text" name="name" id="name" class="form-control">#}
{#                    </div>#}
{##}
{#                    <div class="form-group">#}
{#                        <label for="email">Email</label>#}
{#                        <input type="text" name="email" id="email" class="form-control">#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <!-- ___Send Message___ -->#}
{#                <div class="col-lg-6">#}
{#                    <div class="form-group">#}
{#                        <label for="message">Сообщение</label>#}
{#                        <textarea name="message" id="message" rows="7" class="form-control"></textarea>#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                        <button class="button" type="submit">Отправить</button>#}
{#                    </div>#}
{#                </div>#}
{#            </form><!-- End Form -->#}
{#        </div><!-- End Row -->#}
{#    </div><!-- End Contact Form -->#}
{#    </div>#}

    <div data-scroll-index="5" class="each-section leave-a-comment">
        <h3>Комментировать</h3><a name="comments"></a>
        <div class="comment-form common-border">
            <div class="row">
                {% disqus_show_comments %}
            </div><!-- End Row -->
        </div><!-- End Contact Form -->
    </div>

    <script type="text/javascript">
        var disqus_shortname = 'http-papablog-org';

        (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
        }());
    </script>

</div>
{% endblock content %}
</div>

templates/posts/postlist.html
{% extends "index.html" %}
{% load disqus_tags %}
{% load static %}

{% block content %}

<div class="row">
    {% for obj in object_list %}
        <div class="col-md-12">
            <div class="article-and-feature post-bottom-content one-full-post">
                <h3><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h3>
                <div class="meta-info">
                    <p class="date"><i class="icon-clock"></i>{{ obj.publish|date:"F d, Y" }}</p>
                    <p class="category"><i class="icon-bookmark"></i>  <a href="/{% if obj.category == 'Здоровье' %}health{% elif obj.category == 'Развитие' %}growth{% elif obj.category == 'Вещи' %}things{% elif obj.category == 'Досуг' %}dosug{% endif %}/">{{ obj.category }}</a> </p>
                    <p class="author"><i class="icon-user"></i> by <a href="/user/{{ obj.user }}">{{ obj.user }}</a></p>
                    <p class="comments-count"><i class="icon-commenting"></i> <a href="{{ obj.get_absolute_url }}#disqus_thread" data-disqus-identifier="{{ object.id }}">{% disqus_num_replies %}</a></p>
                </div>
                {% if obj.image %}<div class="img-list">
                    <a href="{{ obj.get_absolute_url }}"><img src="{{ obj.image.url }}" alt="{{ obj.title }}" class="img-responsive"></a>
                {% endif %}</div>
                <div class="single-post-content">
                    <div class="content-markdown">{{ obj.previewText }}</div>
                    <a class="mobile-color" href="{{ obj.get_absolute_url }}"> Читать дальше <i class="fa fa-arrow-right"></i> </a>

                </div>
            </div>
        </div>
    {% endfor %}

    {% include "snippets/pagination.html" %}
</div>

{% endblock content %}