BatyaBlog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.flatpages import urls
from django.contrib.sitemaps.views import sitemap
from posts.sitemap import ASitemap


sitemaps = {
    'posts': ASitemap()
}


urlpatterns = [
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^user/', include("profiles.urls", namespace='profiles')),
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include(urls)),
    url(r'^', include("posts.urls", namespace='posts')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import (
        Mainpage,
        create,
        Detail,
        update,
        delete,
        TagListView,
        robots,
    )


urlpatterns = [
    url(r'^$', Mainpage.as_view(), name='mainpage'),
    url(r'^health/$', Mainpage.as_view(), name='health'),
    url(r'^growth/$', Mainpage.as_view(), name='growth'),
    url(r'^things/$', Mainpage.as_view(), name='things'),
    url(r'^dosug/$', Mainpage.as_view(), name='dosug'),
    url(r'^create/$', create, name='create'),
    url(r'^tag/(?P<slug>[\w-]+)/$', TagListView.as_view(), name='tagged'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/$', Detail.as_view(), name='detail'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/edit/$', update, name='update'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/delete/$', delete),

    url(r'^robots.txt$', robots),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.conf.urls import url
from .views import ProfileDetailView, profile_update
from django.contrib.auth.views import login, logout
from .views import RegisterView, activate_user_view


urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='signup'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='user'),
    url(r'^(?P<username>[\w-]+)/update/$', profile_update, name='update'),
]

posts/models.py
from django.db import models
from django.utils.text import slugify
from unidecode import unidecode
from posts.utils import categories
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from taggit.managers import TaggableManager


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=150, blank=False)
    image = models.ImageField(upload_to=upload_location,
                              null=True, blank=True, height_field='height_field', width_field='width_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    previewText = models.TextField(max_length=260, blank=True)
    fullText = models.TextField()
    slug = models.SlugField(max_length=150, unique=True)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    category = models.CharField(max_length=40, choices=categories(), default='CH')
    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self, *args, **kwargs):
        if self.category == u'Здоровье':
            cat = "health"
        elif self.category == u'Развитие':
            cat = "growth"
        elif self.category == u'Вещи':
            cat = "things"
        elif self.category == u'Досуг':
            cat = "dosug"
        return reverse("posts:detail", kwargs={"category": cat, "slug": self.slug})

    class Meta:
        ordering = ["-timestamp"]


def create_slug(instance, new_slug=None):
    slug = slugify(unidecode(instance.title))
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (instance, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# def user_directory_path(instance):
#     # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
#     return 'avatar/{0}'.format(instance.user.username)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    activation_key = models.CharField(max_length=120)
    gender = models.CharField(max_length=10, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to='avatars/',
                              null=True, blank=True)
    bio = models.TextField(max_length=500, blank=True)

    def __unicode__(self):
        return self.user.username

    def __str__(self):
        return self.user.username

    # def send_activation_email(self):
    #     print("Activation")
    #     pass


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

profiles/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.urls import reverse

from .utils import code_generator
from .models import Profile
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.models import User


class ProfileForm(forms.ModelForm):
    location = forms.CharField(max_length=60)
    bio = forms.TextInput()

    class Meta:
        model = Profile
        fields = ('gender', 'location', 'birth_date', 'bio', 'avatar')


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', )


User = get_user_model()


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        user.save()
        print("Next steps")

        user.profile.activation_key = code_generator()

        path_ = reverse('profiles:activate', kwargs={'code': user.profile.activation_key})
        subject = 'Активация аккаунта papablog.org'
        from_email = settings.DEFAULT_FROM_EMAIL
        message = 'This is my test message'
        recipient = [self.cleaned_data.get("email")]
        html_message = '<p>Привет, {name}!</p><br>' \
                       '<p>Для завершения регистрации пройдите по ссылке: {key}</p>'.format(name=user.username, key=path_)

        send_mail(subject, message, from_email, recipient, fail_silently=False, html_message=html_message)

        if commit:
            user.save()
        return user

profiles/views.py
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth import get_user_model
from profiles.models import Profile
from .forms import ProfileForm, UserForm, RegisterForm


User = get_user_model()


class ProfileDetailView(DetailView):
    template_name = 'user.html'

    def get_object(self, queryset=None):
        username = self.kwargs.get('username', None)
        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)


def profile_update(request, *args, **kwargs):
    user_form = UserForm(request.POST, instance=request.user)
    profile_form = ProfileForm(request.POST, instance=request.user.profile)
    if request.method == 'POST':

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Ваш профиль был успешно обновлен!')
            return render(request, 'user.html', {})
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'update.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('posts:mainpage')


def activate_user_view(request, code=None, *args, **kwargs):
    if code:
        qs = Profile.objects.filter(activation_key=code)
        if qs.exists() and qs.count() == 1:
            profile = qs.first()
            if not profile.user.is_active:
                user_ = profile.user
                user_.is_active = True
                user_.save()
                profile.activation_key = False
                profile.save()
                return redirect(reverse_lazy('profiles:login'))
    # invalid code
    return redirect(reverse_lazy('posts:mainpage'))

profiles/templates/update.html
{% extends "index.html" %}
{% load static %}

{% block title %}{{ user.username }} - Страница пользователя{% endblock title %}

<div class="row">
{% block content %}

<div class="col-md-12 w-100">
    <div class="single-post">

    <!-- ___Start Article & Feature___ -->
        <div class="article-and-feature post-bottom-content bg-box-shadow each-section" data-scroll-index="0">
            <h3>{{ user.username }}</h3>

        <hr>
            <div class="article-content">
                <form method="post">
                  {% csrf_token %}
                  {{ user_form.as_p }}
                  {{ profile_form.as_p }}
                  <button type="submit">Сохранить изменения</button>
                </form>
            </div>

        </div><!-- End Article & Feature -->
    </div>
</div>

{% endblock content %}
</div>

profiles/templates/user.html
{% extends "index.html" %}
{% load static %}

{% block title %}{{ user.username }} - Страница пользователя{% endblock title %}

<div class="row">
{% block content %}

<div class="col-md-12 w-100">
    <div class="single-post">

    <!-- ___Start Article & Feature___ -->
        <div class="article-and-feature post-bottom-content bg-box-shadow each-section" data-scroll-index="0">
            <div class="row">
                <div class="col-md-8"><h3>{{ user.username }}</h3></div>
                <div class="col-md-4">
                    {% if user.username == request.user.username %}
                        <a href="{% url 'profiles:update' user.username %}">Редактировать профиль</a>
                    {% endif %}
                </div>
            </div>
            <hr>
            <div class="article-content">
                <div class="row">
                    <div class="col-md-2">
                        {% if user.profile.avatar %}<img src="{{ user.profile.avatar.url }}" />{% endif %}
                    </div>
                    <div class="col-md-9 col-md-offset-1">
                        <p>{% if user.profile.gender %}<b>Пол:</b> {{ user.profile.gender }}{% endif %}</p>
                        <p>{% if user.profile.birth_date %}<b>Дата рождения:</b> {{ user.profile.birth_date }}{% endif %}</p>
                        <p>{% if user.profile.location %}<b>Город:</b> {{ user.profile.location }}{% endif %}</p>
                        <p>{% if user.profile.bio %}<b>Обо мне:</b> {{ user.profile.bio }}{% endif %}</p>
                    </div>
                </div>
            </div>
        <hr>
            <div class="article-content">
                <div class="">
                    <ul>
                        {% for post in user.post_set.all %}
                            <li style="font-size: 24px; padding: 10px 0;">{{ post.title }}</li>
                            <small>{{ post.category }} | {% for tag in post.tags.all %}{{ tag }} {% endfor %}</small>
                            <hr>
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div><!-- End Article & Feature -->
    </div>
</div>

{% endblock content %}
</div>