BatyaBlog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.flatpages import urls
from django.contrib.sitemaps.views import sitemap
from posts.sitemap import ASitemap


sitemaps = {
    'posts': ASitemap()
}


urlpatterns = [
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^user/', include("profiles.urls", namespace='profiles')),
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include(urls)),
    url(r'^', include("posts.urls", namespace='posts')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import (
        Mainpage,
        create,
        Detail,
        update,
        delete,
        TagListView,
        robots,
    )


urlpatterns = [
    url(r'^$', Mainpage.as_view(), name='mainpage'),
    url(r'^health/$', Mainpage.as_view(), name='health'),
    url(r'^growth/$', Mainpage.as_view(), name='growth'),
    url(r'^things/$', Mainpage.as_view(), name='things'),
    url(r'^dosug/$', Mainpage.as_view(), name='dosug'),
    url(r'^create/$', create, name='create'),
    url(r'^tag/(?P<slug>[\w-]+)/$', TagListView.as_view(), name='tagged'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/$', Detail.as_view(), name='detail'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/edit/$', update, name='update'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/delete/$', delete),

    url(r'^robots.txt$', robots),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/copyright.html
<div class="footer text-center">
    <p>Перепечатка материалов допускается только с указанием источника <br>copyrights © 2017 ПапаБлог</p>
</div>

templates/snippets/css.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/highlight.css' %}">			<!-- ===This Style sheet for Highlight === -->
<link rel="stylesheet" href="{% static 'css/Pe-icon-7-stroke.css' %}">			<!-- ===This Style sheet for Stoke Icon === -->
<link rel="stylesheet" href="{% static 'css/meanmenu.css' %}">				<!-- ===This Style sheet for Responsive Menu=== -->
<link rel="stylesheet" href="{% static 'css/animate.css' %}">				<!-- ===This Style sheet for Animations=== -->
<link rel="stylesheet" href="{% static 'css/fontello.css' %}">		<!-- ===This Style sheet for Font Awesome fonts & icons=== -->
<link rel="stylesheet" href="{% static 'css/font.css' %}">					<!-- ===This Style sheet for Font google fonts=== -->
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />		<!-- ===This Style sheet for Bootstrap classes=== -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">				<!-- ===This Style sheet for Styling the full template=== -->
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">			<!-- ===This Style sheet for making the template responsive for all devices=== -->
<link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}" />
{#    <link rel="stylesheet" href="{% static "css/base.css" %}" />#}
<script src="{% static "scripts/modernizr-2.6.2.min.js" %}"></script>

templates/snippets/footer.html
{% load flatpages %}
{% get_flatpages as flatpages %}

<div class="bottom container-fluid">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <div class="useful-links widget">
                <h3>Полезные ссылки</h3>
                <ul class="pull-left">
                  {% for page in flatpages %}
                    <li><a href="/pages{{ page.url }}" title="{{ page.title }}">{{ page.title }}</a></li>
                  {% endfor %}
                    <li><a href="sitemap.xml" title="Карта сайта">Карта сайта</a></li>
                </ul>
            </div>
        </div>
        <!-- End Column -->

        <!-- ___Contact Us___ -->
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <div class="bottom-contact widget">
                <h3>Партнёры</h3>
                <div class="contact-info">

                </div>
            </div>
        </div>
        <!-- End Column -->

        <!-- ___News Letter___ -->
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <div class="newsletter widget">
                <h3>Из инстаграма</h3>
{#                <div class="input-group">#}
{#                    <input type="text" class="form-control no-radius" placeholder="Email">#}
{#                    <span class="input-group-btn  no-radius">#}
{#                        <button class="btn btn-default" type="button">Подписаться</button>#}
{#                    </span>#}
{#                </div><!-- /input-group -->#}
{#                <p>Подпишись и получай еженедельный дайджест лучших новостей.</p>#}
                <img src="https://picsum.photos/600"/>
            </div>
        </div>
        <!-- End Column -->
    </div>
</div>

templates/snippets/mainmenu.html
<div class="category-nav">
    <div id="mega-menu" class="mega-menu">
        <ul>
            <li id="life-style" class="mega-menu-li life-style"><a href="{% url 'posts:mainpage' %}" title="Главная">Главная</a></li>
            <li id="travel" class="mega-menu-li travel"><a href="{% url 'posts:health' %}" title="Здоровье">Здоровье</a></li>
            <li id="sports" class="mega-menu-li sports"><a href="{% url 'posts:growth' %}" title="Развитие">Развитие</a></li>
            <li id="coding" class="mega-menu-li coding"><a href="{% url 'posts:things' %}" title="Вещи">Вещи</a></li>
            <li id="music" class="mega-menu-li music"><a href="{% url 'posts:dosug' %}" title="Досуг">Досуг</a></li>

        </ul>
    </div>
</div>

templates/snippets/messages.html
{% if messages %}
    <div class="row">
    <div class="messages-line">
        <ul class="messages col-sm-11 col-sm-offset-1">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    </div>
{% endif %}

templates/snippets/pagination.html
{% if is_paginated %}
    <div class="pagination">
        {% if page_obj.has_previous %}
            <span><a href="?page={{ page_obj.previous_page_number }}">Назад</a></span>
        {% endif %}
        <span class="current">
            <span>Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
        </span>
        {% if page_obj.has_next %}
            <span><a href="?page={{ page_obj.next_page_number }}">Вперёд</a></span>
        {% endif %}
    </div>
{% endif %}

templates/snippets/scripts.html
{% load static %}
<script src="{% static 'scripts/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'scripts/scripts.js' %}"></script>				<!-- ===This Script for Custom Script=== -->
<script src="{% static 'scripts/bootstrap.min.js' %}"></script>
<script src="{% static 'scripts/wow.min.js' %}"></script>				<!-- ===This Script for Wow JS=== -->
<script src="{% static "scripts/jquery.meanmenu.min.js" %}"></script>
<script src="{% static "scripts/marked.min.js" %}"></script>		<!-- ===This Script for Main Menu=== -->
<script src="{% static "scripts/jquery.jscroll.js" %}"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $(".content-markdown").each(function () {
            var content = $(this).text();
            console.log(content);
            var markedContent = marked(content);
            $(this).html(markedContent);
        });
    });
</script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter47570515 = new Ya.Metrika2({
                    id:47570515,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/tag.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks2");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/47570515" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

templates/snippets/sidebar.html
{% load static %}


<div id="menu-area" class="menu-area toogle-sidebar-sections">
    <div class="menu-head">
        <a href="#0" class="accordion-toggle">Меню <span class="toggle-icon"><i class="icon-menu"></i></span></a>
        <div class="accordion-content">
            <div class="menu-body">
                <ul>
                    <li class="home"><a href="/">Главная</a></li>
                    <li><a href="#">Мероприятия</a></li>
                    <li class="sm-post"><a href="#">Магазин</a></li>
                    <li class="sm-post"><a href="#">Блоги</a></li>
                </ul>
            </div><!-- End Menu Body -->
        </div><!-- End According Content -->
    </div><!-- End Menu Head -->
</div>

<div class="top-rated-area toogle-sidebar-sections">
    <div class="top-rated-head">
        <a href="#0" class="accordion-toggle">Статистика <span class="toggle-icon"><i class="icon-menu"></i></span></a>
        <div class="accordion-content">

            <!-- ___Start Top Rated Body___ -->
            <div class="top-rated-body">

                <a href="#0" class="top-rated-item javascript">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%;">
                        </div>
                    </div>
                    <div class="top-rated-heading">Записей</div>

                    <div class="top-rated-count">
                        <div class="progress-score">
                            <i class="fa fa-eye"></i>
                            <span>2564</span>
                        </div>
                    </div>
                </a>
                <!-- End Java Script -->

                <a href="#0" class="top-rated-item iphone">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="23" aria-valuemin="0" aria-valuemax="100" style="width: 23%;">
                        <span class="sr-only">60% Complete</span>
                        </div>
                    </div>
                    <div class="top-rated-heading">Комментариев</div>

                    <div class="top-rated-count">
                        <div class="progress-score">
                            <i class="fa fa-eye"></i>
                            <span>2564</span>
                        </div>
                    </div>
                </a>
                <!-- End Iphone -->

                <a href="#0" class="top-rated-item top-hills">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="43" aria-valuemin="0" aria-valuemax="100" style="width: 43%;">
                        <span class="sr-only">60% Complete</span>
                        </div>
                    </div>
                    <div class="top-rated-heading">Тем на форуме</div>

                    <div class="top-rated-count">
                        <div class="progress-score">
                            <i class="fa fa-eye"></i>
                            <span>2564</span>
                        </div>
                    </div>
                </a>
                <!-- End Top Hills -->

                <!-- End Wordpress -->

                <a href="#0" class="top-rated-item ebola-virus">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="82" aria-valuemin="0" aria-valuemax="100" style="width: 22%;">
                        <span class="sr-only">80% Complete</span>
                        </div>
                    </div>
                    <div class="top-rated-heading">Пользователей</div>

                    <div class="top-rated-count">
                        <div class="progress-score">
                            <i class="fa fa-eye"></i>
                            <span>2564</span>
                        </div>
                    </div>
                </a><!-- End Ebola Virus -->

            </div><!-- End Top Rated Body -->
        </div><!-- End Accordion Content -->
    </div><!-- End Top Rated Head -->
</div>

{#<div class="follow-area toogle-sidebar-sections">#}
{#    <div class="follow-head">#}
{#        <a href="#0" class="accordion-toggle">Соцсети <span class="toggle-icon"><i class="icon-menu"></i></span></a>#}
{#        <div class="accordion-content">#}
{#            <div class="follow-body">#}
{#                <ul class="ul-clearfix">#}
{#                    <li>#}
{#                        <a href="#0" class="connect-with-us facebook">#}
{#                            <i class="icon-facebook"></i>#}
{#                            <span>11,222 Follow</span>#}
{#                            <div class="plus">#}
{#                                <i class="icon-plus"></i>#}
{#                            </div>#}
{#                        </a><!-- End Facebook -->#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#0" class="connect-with-us twitter">#}
{#                            <i class="icon-twitter"></i>#}
{#                            <span>9865 Follow</span>#}
{#                            <div class="plus">#}
{#                                <i class="icon-plus"></i>#}
{#                            </div>#}
{#                        </a><!-- End Twitter -->#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#0" class="connect-with-us google-plus">#}
{#                            <i class="icon-gplus"></i>#}
{#                            <span>2864 Follow</span>#}
{#                            <div class="plus">#}
{#                                <i class="icon-plus"></i>#}
{#                            </div>#}
{#                        </a><!-- End Google Plus -->#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#0" class="connect-with-us linkedin">#}
{#                            <i class="icon-linkedin"></i>#}
{#                            <span>11,222 Follow</span>#}
{#                            <div class="plus">#}
{#                                <i class="icon-plus"></i>#}
{#                            </div>#}
{#                        </a><!-- End Linkedin -->#}
{#                    </li>#}
{#                </ul>#}
{#            </div><!-- End follow-body -->#}
{#        </div><!-- End Accordion Content -->#}
{#    </div><!-- End Follow Head -->#}
{#</div>#}


{#<p>#}
{#{% for tag in all_tags %}#}
{#    <a href="{% url "posts:tagged" tag.slug %}">{{ tag.name }}</a>,#}
{#{% endfor %}#}
{#</p>#}

templates/snippets/sidebarcontent.html
{% load static %}

<div class="sidebar">
{#    <div class="sidebar-widget sidebar-tab">#}
{#        <div role="tabpanel">#}
{#            <!-- Nav Tabs -->#}
{#            <ul class="nav nav-tabs" role="tablist">#}
{#                <li role="presentation" class="active"><a href="#popular" aria-controls="popular" role="tab" data-toggle="tab">Popular</a></li>#}
{#                <li role="presentation"><a href="#video" aria-controls="video" role="tab" data-toggle="tab">Video</a></li>#}
{#                <li role="presentation"><a href="#tag" aria-controls="tag" role="tab" data-toggle="tab">Tag</a></li>#}
{#            </ul>#}
{##}
{#            <!-- ___Tab Content___ -->#}
{#            <div class="tab-content">#}
{#                <!-- ___Tab Pane Popular___ -->#}
{#                <div role="tabpanel" class="tab-pane fade in active" id="popular">#}
{#                    <ul>#}
{#                        <li>#}
{#                            <div class="media">#}
{#                                <div class="media-body media-left">#}
{#                                    <h3>travel experience sahara desert</h3>#}
{#                                    <span>Jan 20, 2017</span>#}
{#                                    <p class="travel-color">Travel</p>#}
{#                                </div>#}
{#                                <div class="media-right">#}
{#                                    <img class="img-responsive" src="images/widget/widget-tag-1.jpg" alt="">#}
{#                                </div>#}
{#                            </div><!-- End Media -->#}
{#                        </li>#}
{##}
{#                        <li>#}
{#                            <div class="media">#}
{#                                <div class="media-body media-left">#}
{#                                    <h3>Now get a stranger to wake you up </h3>#}
{#                                    <span>Jan 20, 2017</span>#}
{#                                    <p class="mobile-color">Mobile</p>#}
{#                                </div>#}
{#                                <div class="media-right">#}
{#                                    <img class="img-responsive" src="images/widget/widget-tag-2.jpg" alt="">#}
{#                                </div>#}
{#                            </div><!-- End Media -->#}
{#                        </li>#}
{##}
{#                        <li>#}
{#                            <div class="media">#}
{#                                <div class="media-body media-left">#}
{#                                    <h3>Kids must vision check-up regularly</h3>#}
{#                                    <span>Jan 20, 2017</span>#}
{#                                    <p class="health-color">Health</p>#}
{#                                </div>#}
{#                                <div class="media-right">#}
{#                                    <img class="img-responsive" src="images/widget/widget-tag-3.jpg" alt="">#}
{#                                </div>#}
{#                            </div><!-- End Media -->#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#                <!-- End Tab Pane Popular -->#}
{##}
{#                <!-- ___Tab Pane Video___ -->#}
{#                <div role="tabpanel" class="tab-pane fade" id="video">#}
{#                    <ul>#}
{#                        <li>#}
{#                            <div class="media">#}
{#                                <div class="media-body media-left">#}
{#                                    <h3>Now get a stranger to wake you up </h3>#}
{#                                    <span>Jan 20, 2017</span>#}
{#                                    <p class="mobile-color">Mobile</p>#}
{#                                </div>#}
{#                                <div class="media-right">#}
{#                                    <img class="img-responsive" src="images/widget/widget-tag-3.jpg" alt="">#}
{#                                </div>#}
{#                            </div><!-- End Media -->#}
{#                        </li>#}
{##}
{#                        <li>#}
{#                            <div class="media">#}
{#                                <div class="media-body media-left">#}
{#                                    <h3>travel experience sahara desert</h3>#}
{#                                    <span>Jan 20, 2017</span>#}
{#                                    <p class="travel-color">Travel</p>#}
{#                                </div>#}
{#                                <div class="media-right">#}
{#                                    <img class="img-responsive" src="images/widget/widget-tag-1.jpg" alt="">#}
{#                                </div>#}
{#                            </div><!-- End Media -->#}
{#                        </li>#}
{##}
{#                        <li>#}
{#                            <div class="media">#}
{#                                <div class="media-body media-left">#}
{#                                    <h3>Kids must vision check-up regularly</h3>#}
{#                                    <span>Jan 20, 2017</span>#}
{#                                    <p class="health-color">Health</p>#}
{#                                </div>#}
{#                                <div class="media-right">#}
{#                                    <img class="img-responsive" src="images/widget/widget-tag-2.jpg" alt="">#}
{#                                </div>#}
{#                            </div><!-- End Media -->#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#                <!-- End Tab Pane Video -->#}
{##}
{#                <!-- ___Tab Pane Tag___ -->#}
{#                <div role="tabpanel" class="tab-pane fade" id="tag">#}
{#                    <ul>#}
{#                        <li>#}
{#                            <div class="media">#}
{#                                <div class="media-body media-left">#}
{#                                    <h3>travel experience sahara desert</h3>#}
{#                                    <span>Jan 20, 2017</span>#}
{#                                    <p class="travel-color">Travel</p>#}
{#                                </div>#}
{#                                <div class="media-right">#}
{#                                    <img class="img-responsive" src="images/widget/widget-tag-2.jpg" alt="">#}
{#                                </div>#}
{#                            </div><!-- End Media -->#}
{#                        </li>#}
{##}
{#                        <li>#}
{#                            <div class="media">#}
{#                                <div class="media-body media-left">#}
{#                                    <h3>Kids must vision check-up regularly</h3>#}
{#                                    <span>Jan 20, 2017</span>#}
{#                                    <p class="health-color">Health</p>#}
{#                                </div>#}
{#                                <div class="media-right">#}
{#                                    <img class="img-responsive" src="images/widget/widget-tag-3.jpg" alt="">#}
{#                                </div>#}
{#                            </div><!-- End Media -->#}
{#                        </li>#}
{##}
{#                        <li>#}
{#                            <div class="media">#}
{#                                <div class="media-body media-left">#}
{#                                    <h3>Now get a stranger to wake you up </h3>#}
{#                                    <span>Jan 20, 2017</span>#}
{#                                    <p class="mobile-color">Mobile</p>#}
{#                                </div>#}
{#                                <div class="media-right">#}
{#                                    <img class="img-responsive" src="images/widget/widget-tag-1.jpg" alt="">#}
{#                                </div>#}
{#                            </div><!-- End Media -->#}
{#                        </li>#}
{#                    </ul>#}
{#                </div><!-- End Tab Pane Tag-->#}
{#            </div><!-- End Tab Content -->#}
{#        </div><!-- End Tab Panel -->#}
{#    </div><!-- End Side Tab -->#}

    <!-- ___Start Sidebar___ -->
    <div class="sidebar-widget sidebar-about">
        <h3>Что за...</h3>
        <div class="about-image">
            <img class="img-responsive" src="{% static 'images/about.jpg' %}" alt="О сайте" />
        </div>
        <p><b>Папа Блог</b> - сайт для родителей. Место, где люди могут поделиться опытом и задать волнующий их вопрос.</p>
    </div> <!-- End Side About -->

{#    <!-- ___Start Sidebar Slider___ -->#}
{#    <div class="sidebar-widget sidebar-slider">#}
{#        <div id="sidebar-slide-post" class="carousel slide" data-ride="carousel">#}
{#            <!-- ___Wrapper for Slides___ -->#}
{#            <div class="carousel-inner" role="listbox">#}
{#                <div class="item active">#}
{#                    <img class="img-responsive" src="{% static 'images/about.jpg' %}" alt="">#}
{#                </div>#}
{#                <div class="item">#}
{#                    <img class="img-responsive" src="{% static 'images/about.jpg' %}" alt="">#}
{#                </div>#}
{#                <div class="item">#}
{#                    <img class="img-responsive" src="{% static 'images/about.jpg' %}" alt="">#}
{#                </div>#}
{#            </div>#}
{##}
{#            <!-- Controls -->#}
{#            <div class="slider-controls">#}
{#                <a class="left carousel-control" href="#sidebar-slide-post" role="button" data-slide="prev">#}
{#                    <i class="fa fa-angle-left"></i>#}
{#                </a>#}
{#                <a class="right carousel-control" href="#sidebar-slide-post" role="button" data-slide="next">#}
{#                    <i class="fa fa-angle-right"></i>#}
{#                </a>#}
{#            </div>#}
{#        </div> <!-- End Carousel -->#}
{#    </div> <!-- End Sidebar Slider -->#}

    <div class="sidebar-widget sidebar-ads">
        <img class="img-responsive" src="{% static 'images/bellakt.png' %}" alt="" />
    </div>
</div>

templates/snippets/slideshow.html
{% load static %}
<div class="container">
    <div class="row">
        <!-- BEGIN HEADER -->
        <div id="row">
          <div class="logo img-responsive col-md-3 col-md-offset-1"> <a href="#"><img src="{% static 'images/logo.png' %}" alt="" /></a> </div>
          <div class="ad img-responsive col-md-4">
            <p>Баннер</p>
          </div>
          <div class="ad img-responsive col-md-3">
            <p>Профиль</p>
          </div>
        </div>
        <!-- END HEADER -->
    </div>
</div>

templates/snippets/topbar.html
<div class="top-bar">
    <div class="top-bar-head">
        <div class="search">
            <i class="icon-search showSingle" id="1"></i>
            <p>Ищем что-то конкретное?</p>
        </div>
        <div class="login-user pull-right showSingle" id="2">
            <i class="icon-user-circle-o"></i>
        </div>

        <div class="login-mail pull-right showSingle" id="3">
            <i class="icon-mail"></i>
        </div>
    </div>
    <!-- End Top Bar Head -->

    <!-- ___Start Top Bar Body___ -->
    <div class="top-bar-body">
        <div class="search-body targetDiv" id="div1">
            <p>Поиск</p>
            <form method="get" action="">
                <input type="text" name="q" class="form-control no-radius" placeholder="Введите фразу для поиска" value="{{ request.GET.q }}">
            </form>
        </div>

        <!-- ___Start Top Bar Login Body___ -->
        {% if request.user.is_authenticated %}
            <div class="user-body targetDiv" id="div2">
                <div class="row">
                    <div class="col-md-4">Вы уже залогинены, {{ user.username }}.</div>
                    <div class="col-md-8">
                        <form action="/create"><button type="submit" class="btn btn-default form-control no-radius">Добавить запись</button></form>
                        <form action="/user/logout"><button type="submit" class="btn btn-default form-control no-radius">Выйти</button></form>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="user-body targetDiv" id="div2">
            <div class="row">
{#                <div class="col-md-6">#}
{#                    <div class="login-account">#}
{#                        <p>Войти</p>#}
{#                        <form>#}
{#                            <div class="form-group">#}
{#                                <input type="text" class="form-control no-radius" placeholder="Имя пользователя">#}
{#                            </div>#}
{#                            <div class="input-group">#}
{#                                <input type="text" class="form-control no-radius" placeholder="Пароль">#}
{#                                <span class="input-group-btn">#}
{#                                    <button class="btn btn-default" type="button">OK</button>#}
{#                                </span>#}
{#                            </div><!-- Input Group -->#}
{#                            <div class="forgot-pass">Забыли <a href="#">пароль?</a></div>#}
{#                        </form>#}
{#                    </div><!-- End Login Account -->#}
{#                </div><!-- End Column -->#}
                <div class="col-md-6">
                    <div class="register">
                        <p>Уже есть аккаунт?</p>
                        <form action="/user/login"><button type="submit" class="btn btn-default form-control no-radius">Войти</button></form>
                    </div>
                </div>

                <div class="dashed-divider"></div>
                <div class="col-md-6">
                    <div class="register">
                        <p>Новый пользователь?</p>
                        <form action="/user/register"><button type="submit" class="btn btn-default form-control no-radius">Зарегистрироваться</button></form>
                    </div>
                </div><!-- End Column -->
            </div><!-- End Row -->
        </div>
        {% endif %}
        <!-- End Top Bar Login Body -->
    </div><!-- End Top Bar Body -->
</div>